### ISSUE TITLE
Cursor not hidden when locking session

### ISSUE THREAD

**Issue by charbelnicolas** [ifreund/waylock#65] opened 2023-11-14 01:57 UTC
At the moment when you lock the screen the cursor still shows unless you move it and only then it disappears.

It would be nice to hide the cursor when locking the session.

My locked screen has the exact same color background as when it is unlocked so there is no way to visually tell if it got locked or not. (I don't use any bars, just a plain colored background.

I could of course change the color when locked but that's not the point.

**Comment by ifreund** [comment] 2023-11-14 09:18
What river version are you using? (`river -version` will tell you)

**Comment by charbelnicolas** [comment] 2023-11-14 12:50
Hello @ifreund, I'm using river version 0.3.0-dev.153+c50ed9c

**Comment by ifreund** [comment] 2023-11-14 14:24
Ok, and what screenlocker program are you using? I can't reproduce this with waylock...

**Comment by charbelnicolas** [comment] 2023-11-14 19:40
I'm using waylock 0.6.3 and I'm on Arch Linux... I have an intel integrated graphics card with an i7-13700k processor... I'm not really using seatd, I don't know if that makes any difference (it is installed though).

This is the init command I have mapped to enable waylock:

riverctl map normal Super+Shift L spawn 'waylock -init-color 0x333333 -input-color 0x555555 -fail-color 0xf57d7d'

**Comment by ifreund** [comment] 2023-11-17 14:06
Does this happen every time for you? I still can't manage to reproduce this for whatever reason or see how it might happen from the code.

**Comment by charbelnicolas** [comment] 2023-11-17 14:10
> Does this happen every time for you? I still can't manage to reproduce this for whatever reason or see how it might happen from the code.

Yes, it happens every single time, and it also happens with _swaylock_ so it might be something else other than waylock. I'll try and see if I can reproduce it with hyprland.

**Comment by ifreund** [comment] 2023-11-17 14:48
>Yes, it happens every single time, and it also happens with swaylock so it might be something else other than waylock. I'll try and see if I can reproduce it with hyprland.

It's a bug with river, not waylock or swaylock. If a similar bug happens under a different compositor that's likely unrelated.

**Comment by ifreund** [comment] 2023-11-17 17:54
Ok, I think I've figured out what's happening here. I was quite confused as river should trigger the `wl_pointer.enter` event that leads to the cursor being hidden by waylock here: https://github.com/riverwm/river/blob/68366c733176d131c9a64d51886f8428664148a1/river/LockSurface.zig#L115 However, it appears that the wlr_scene node for the surface has size 0x0 when wlroots emits the `wlr_session_lock_surface.map` signal. As far as I can tell, the order of events is as follows:

1. a lock surface is created, the wlroots session lock implementation sets up a commit handler for the surface
2. river is notified of the surface with the new_surface event and creates a scene surface, which also sets up a commit handler
3. the client attaches and commits the first buffer
4. the wlroots session lock commit handler is called since it was set up first, it emits the map event for the session lock surface
5. the scene surface's commit handler is called. It modifies state to add the newly committed buffer to the scene
before 5 is done, the scene node will have 0 size since there is no buffer, meaning that the scene_node_at() call used to find the surface to send a pointer enter to will not find anything.

The reason I was having trouble reproducing this is that I happen to have 2 output on the computer I was testing on which means that this appears to work as expected on one of the outputs.

Now that I understand the problem, I'll see about the right way to fix this.

**Comment by ifreund** [comment] 2023-11-17 18:52
Should be fixed by river commit https://github.com/riverwm/river/commit/50ccd4c5b3cd700bed09d26eb75552f08f9af262

**Closed by ifreund** 2023-11-17 18:52 UTC

**Comment by charbelnicolas** [comment] 2023-11-17 19:38
That's great to hear! Thank you!
